### ISSUE TITLE
Auto closes when trying to import runes .

### ISSUE THREAD

**Issue by Smug-Kayle** [Rokuazery/LoL-Assist#24]
https://file.io/pcZczfc2cy1N log file : )

**Comment by Rokuazery** [comment]
Were you using METASrc as the rune and spells source?

**Comment by xerus6** [comment]
> Were you using METASrc as the rune and spells source?

I just tried and had the same issue on both u.gg and metasrc, this happens when there is nothing selected on the role menu 
![image](https://user-images.githubusercontent.com/45909555/236624961-19211af3-f6c0-4dcc-8b9e-b768f9599f6a.png)
Meaning I have to manually select the role before locking the champion otherwise it will crash.

**Comment by xerus6** [comment]
@Rokuazery ☝☝
