### ISSUE TITLE
Don't replace existing runes and take just one

### ISSUE THREAD

**Issue by owlnai** [Rokuazery/LoL-Assist#4]
Hey there, amazing app! There's one thing I would like to request. I had a few rune pages that I manually set before downloading LoL-Assist, but it seems the tool uses a new rune page every time you change your champion and they disappeared, so you could end up with multiple rune pages taken at the same lobby. 

It would be nice if it could track the current rune page and change that one instead of taking the others.
![image](https://user-images.githubusercontent.com/20427094/152672302-64c4cabc-87f8-4514-95cd-4f4563ff8db7.png)

- App version: 1.5.8.0
- Lib version: 1.0.8.0 
- OS: Windows 11 Pro 22543.1000 (Insider)

**Comment by Rokuazery** [comment]
Thank you for your suggestion, I'll try to implement your request in the future update.

**Comment by Rokuazery** [comment]
After investigating this issue, it seems like it was already "tracking" the current Rune Page. It creates a new Rune Page if there's no editable slot found. And it replaced an editable Rune Page if it's at the maximum limit for creating a new Rune Page. Unfortunately, I can't replicate this issue you're having. It might be because you have more than 2 editable Rune Page, but I'm not sure if that's the case. I'll close this issue temporarily for now, sorry.

**Comment by owlnai** [comment]
Oops, you're right! It seems it was an odd issue with the League of Legends UI, because I restarted the client and my old rune pages are now back and there's just one Lol-Assist page 😅
